---
title: "Final Project: Technical Report"
subtitle: Data Analytics and Visualization, Fall 2024
author: Otis Golden and Simone Johnson
institute: Harvey Mudd College
date: December 9th 2024
format: 
  html:
    self-contained: true
    code-fold: true
---

# Data Collection and Processing

The original source of the data for this project is Federal Bureau of Investigation's (FBI) Uniform Crime Reporting (UCR) Program, but we are planning on getting the data from Inter-university Consortium for Political and Social Research (ICPSR) at the University of Michigan as they have compiled and processed the data into an easier format for us to manipulate for this project. The link for this data is: https://www.icpsr.umich.edu/web/NACJD/studies/38795. The data includes the state, month, police agency, and offense code of each arrest. Additionally, most of the observations include demographic information for the people involved in the arrest such as their age, gender, and ethnicity. This dataset is appropriate for this topic because it contains the data drawn from the Uniform Crime Report's Return A form that is published by the FBI (Federal Bureau of Investigation) which police agencies (voluntarily) fill out and return every month. This form contains information on the number of arrests for each offense and demographic information from that agency. 

An additional dataset we inclluded was the US states population breakdown, including information about race. This was needed to fairly compare the rates of marijuana arrest by race. This data allowed us to normalize the arrest counts against the population size of each racial group studied within each state. Without this, we would have been simply comparing the raw counts of arrests based on race, and would not have been accounting for the difference in the population size of each group which would probably create misleading visualizations and conclusions

One common data processing decision was excluding the n/a or no information given cases. We did this initially by filtering out cases where there was no race, ethnicity, or sex information filed and then further when looking at a specific offense we also did not count where the demographic information was 99998 or 99999 which was used to indicate a null or not applicable cell. When we lacked information for a state, we simply decided to create a color for a state that didn't have information rather than reporting 0 for that state.

Additionally we perfomed joins on our dataset for instance joining with the US population break down dataset, as well as multiple groupings by max, count, normalized sum, etc. 

# Visualization Choices

We decided to go for a variety of visualization techniques to better retain the viewer and to enrich the expressiveness of our article. 

The interactive map visualization was chosen to put into context the difference in Marijuana arrest data by race and by state. The side-by-side showing allows for a quick comparison between two different races. One of our main choices in the analysis of this dataset was to plot the information geospatially because states have unique policies regarding marijuana possession which would affect the arrest rate for this arrest code. Some alternate visualizations we considered for this subset of data were a bar chart to represent the amount of arrests per state, as well as just a single map without interaction that plotted a ratio between two given demographics. However, we decided that the bar chart wouldn't be that suitable because the ordering of the bars wouldn't be as clear as just having the states be part of a map as well as it would be a lot of bars to display, so it might be hard to format in a easy to interpret way. Also the ratio map wouldn't be as effective because it would only display one pair of demographics, as well as that it might be harder to interpret rather than plotting a rate as we ended up doing. 

Additionally since we were dealing with state and crime categorical data we decided to go with a pie chart and a circular bar chart to better show count. We chose the circular bar chart over the straight bar chart as to proided an easier way to compare amoungst the same group, and to fit all 50 states without overlap. The coloring and grouping of the circular bar chart also allowed us to show what offense was most prevalent, as well as the count being represented by the size of the bar. 

Similar to the side-by-side plot for marijuana charges, the faceted pie chart allows for quick comparison of the crime data across races. A different plot that we considered for this representation was another bar chart that was faceted, but we found that it was easier to compare between the racial groups using the pie charts.

# Alignment with Goals

The goal of this article was to be able to look at important issues regarding crime and biased arrest rates. Our visualizations and analysis explores these concepts through looking at the arrest offenses broken down by race and through creating a decision tre classifier to determine if there is a correlation between the racial distribution and the type of arrest. Additionally, we looked at one offence in particular, marijuana possession, and analyzed if there was a difference in the arrest rates across the races. Through our visualizations we have shown that there is a clear racial bias for crimes like Drug Abuse and DUI, and that the extent of this might vary from state to state depending on policies. 

# Statistical Models and Techniques

We Used A Decision Tree Classifier to determine if there was some form of bias between racial distribution and the type of arrests, and determine that given a percentage of a certain we can determine what the offense they were arrested for 0.6 of the times.

Additionally, we calculated the proportions of people arrested for marijuana charges, however, this is a population parameter because it is using all of the arrest data rather than a sample from the US, so we didn't have to calculate an uncertainty value for our proportions.